### ISSUE TITLE
Cherry leaves turn black with this mod installed

### ISSUE THREAD

**Issue by Tempest-5ky** [Zuiron/Photosynthesis#227] opened 2024-01-29 21:51 UTC
hello! Having an odd issue where installing this mod turns cherry leaf blocks completely black in-world. The item texture is unaffected.
![image](https://github.com/Zuiron/Photosynthesis/assets/99220350/2873305c-2230-46bc-97ba-4082c28f40b0)

Minecraft Fabric 1.20.1, mod version 0.0.20

**Comment by Zuiron** [comment] 2024-01-30 17:00
Need a full log and mod list

**Comment by Tempest-5ky** [comment] 2024-02-01 23:54
Sorry for the delay!

Log: https://mclo.gs/haY5OgD
mod list is listed on the log from line 117 to 433

**Comment by Tempest-5ky** [comment] 2024-02-03 19:31
update: this seems to affect all of Photosynthesis' leaves
![image](https://github.com/Zuiron/Photosynthesis/assets/99220350/892aa463-8c6a-404a-887b-ad953c696a53)

**Comment by Zuiron** [comment] 2024-02-19 01:01
![fancy](https://github.com/Zuiron/Photosynthesis/assets/5185131/c0464049-36e3-4e51-b232-5b92552211ac)
hmm. log doesn't say anything is wrong with my mod. like anywhere... however it does spew errors for other mods. there might be some other mods conflicting with each other which might cause this.

or it might actually be something else, can you try set graphics to fancy for leaves?

**Comment by Tempest-5ky** [comment] 2024-02-19 03:51
I’ll look into it via binary search, though I didn’t see any errors
relating to photosynthesis leaves when looking through the logs. This is
definitely an odd one.

**Comment by Zuiron** [comment] 2024-02-19 03:54
can you try with fancy graphics? when you can, I'm curious if that might be the cause xD

**Comment by Tempest-5ky** [comment] 2024-02-19 04:08
Unfortunately, that doesn't fix the issue :/
It doesn't seem to be the primary suspects (leaf culling via MoreCulling, or some kind of breakage from PassableLeaves), so I'll do a proper binary search tomorrow to find the suspect.

**Comment by Zuiron** [comment] 2024-02-19 04:10
alright, if there is an issue on my end i would really like to know and fix it asap :)

**Comment by Tempest-5ky** [comment] 2024-02-29 20:06
I'm so so sorry for the delay- life got busy and I forgot to do this!
I can confirm that the issue happens even if Photosynthesis and its dependencies are the only mods loaded.
![image](https://github.com/Zuiron/Photosynthesis/assets/99220350/36bd43fc-326f-474d-9fbd-c58ee1438b28)
![image](https://github.com/Zuiron/Photosynthesis/assets/99220350/52ab83f8-5953-4a9d-9307-c56a9472267e)

**Comment by Tempest-5ky** [comment] 2024-02-29 20:08
The latest.log doesn't seem to show any issues save for some texture, sound, and recipe errors
https://mclo.gs/4aTcPkh

**Comment by Tempest-5ky** [comment] 2024-02-29 20:11
Ah- alright, when Photosynthesis is the only mod, setting graphics to 'fancy' does fix the issue. Hopefully that helps! If it could be fixed for people with weaker computers that need the graphics on Fast, that would be excellent :D

**Comment by Tempest-5ky** [comment] 2024-02-29 20:15
This seems to only partially affect some leaves, and fully affect others. In all cases, it makes the normally transparent sections completely black. I'm aware that this is a normal thing with the 'fast' setting, as vanilla leaves do something similar, though something seems off for those that have gone completely black.
Fast graphics:
![image](https://github.com/Zuiron/Photosynthesis/assets/99220350/8bf65a65-308c-48da-9c2a-20e4f4c9430e)
From left to right: Apple, Banana, Cinnamon, Orange, Pear, Coconut, Avocado, Cherry (all-black), Lemon

Fancy graphics:
![image](https://github.com/Zuiron/Photosynthesis/assets/99220350/4ea15c49-1051-4458-a963-95c8cb79aae9)

**Comment by Zuiron** [comment] 2024-02-29 21:44
ok i know exactly why this is happening now. its because of the custom leaves block with overlay. not sure why its blacked out but. i will definately investigate and see if it can be resolved. thanks for reporting this! its definitely on my end issue.

**Comment by Zuiron** [comment] 2024-02-29 22:07
you know what. its actually not possible to fix this per say. 
the only way to actually fix this. is to bundle an "resource pack" with the season support leaves separately. because the season overlay block ONLY works on fancy leaves.

**Comment by Zuiron** [comment] 2024-02-29 22:08
I will actually do that because the season leaves are quiet resource heavy. thanks for this!

**Comment by Zuiron** [comment] 2024-02-29 22:10
oh and just to mention it. why its only happening to a few and not others is because the season leaves thing i have only applied to a couple leaves, mainly vanilla and a couple of my own trees just to test it out :P

**Comment by Tempest-5ky** [comment] 2024-02-29 22:15
No worries! Thank you sm for the fix :D

**Comment by Zuiron** [comment] 2024-03-17 14:57
issue now resolved with latest release. can download now at modrinth: https://modrinth.com/mod/photosynthesis/version/1.20.1-0.0.21

**Closed as completed by Zuiron** 2024-03-17 14:57 UTC
Labels: solved, TODO

**Comment by Zuiron** [comment] 2024-03-17 14:58
oh and. just dont use the optional builtin resoucepack on FANCY graphics. you can now use FAST graphics without issues :)
